services:
  boxteadev:
    build: .
    container_name: boxteadev
    env_file:
      - .env
    environment:
      - DEBUG=True
      - SESSION_TOKEN=temporarydevkey_dontuseinprod
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./data:/app/data
    command: /app/starter.sh